###########
# site.title

title:    'Multi agent hide and seek'
subtitle: 'CS 175: Project in AI (in Minecraft)'


#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md
